### ISSUE TITLE
No output from smgsm_08 coord transform function

### ISSUE THREAD

**Issue by laurajfryer** [johncoxon/tsyganenko#5]
After running the trace_08 function, I then want to transform gsw cartesian coordinates to sm coordinates using smgsm_08. When I run this function the code doesn't produce an output. 

![image](https://user-images.githubusercontent.com/58478803/83754761-6cc4d200-a664-11ea-8a58-2c38f677d1d4.png)

![image](https://user-images.githubusercontent.com/58478803/83754788-78b09400-a664-11ea-9eb2-28ebe2719922.png)

**Comment by johncoxon** [comment]
Hi Laura, thanks for the bug report. I've edited the module so that you ought to be able to call the majority of the Fortran subroutines from Geopack in this way now. Please could you install the version of the repo at ba0e4c02d56ea40275c88774d81704b7c7b1a584 and tell me if that fixes your issue?

**Comment by johncoxon** [comment]
Having confirmed with @laurajfryer that the bug fix addresses the problem, this issue can be closed.
